### ISSUE TITLE
S1F17 Go Online runs into ValueError exception, receives response only afterwards

### ISSUE THREAD

**Issue by alanchev** [bparzella/secsgem#158]
Help! I have troubles receiving the response to a *S1F17 Go Online* that I initiate myself with `secsgem.gem.GemHostHandler.go_online()`, no matter if I'm talking to an actual equipment or against a test application. In this case, I am talking to a test app.

I'm using the lib's release version 0.2.0.

The following code:

```python
from __future__ import annotations
import secsgem.common
import secsgem.gem
import secsgem.hsms
import secsgem.secs
import secsgem.secs.functions._all
import secsgem.secs.functions.streams_functions

class MyFaultyHandler(secsgem.gem.GemHostHandler):
    def __init__(self):

        super().__init__(secsgem.hsms.HsmsSettings(
            device_type=secsgem.common.DeviceType.HOST,
            connect_mode=secsgem.hsms.HsmsConnectMode.ACTIVE,
            address="127.0.0.1",
            port=5000,
            session_id=10
        ))
        
        self.events.handler_communicating += self._on_connected
        
        self.enable()


    def _on_connected(self, params: dict):     
        self.go_online()

```

consistently outputs the following log:

```
24.09.2024 10:00:00 [secsgem.gem.communication_state_machine.CommunicationStateMachine][DEBUG   ][state_machine.py:0235] State change: DISABLED >> NOT_COMMUNICATING
24.09.2024 10:00:00 [m200.faulty.MyFaultyHandler.MyFaultyHandler][INFO    ][handler.py:0086] Connection enabled
24.09.2024 10:00:00 [secsgem.common.tcp_client_connection.TcpClientConnection][DEBUG   ][tcp_client_connection.py:0155] connecting to 127.0.0.1:5000
24.09.2024 10:00:00 [secsgem.hsms.connection_state_machine.ConnectionStateMachine][DEBUG   ][state_machine.py:0235] State change: NOT_CONNECTED >> CONNECTED_NOT_SELECTED
24.09.2024 10:00:00 [communication][INFO    ][protocol.py:0366] > 'header': {session_id:0xffff, stream:00, function:00, p_type:0x00, s_type:0x01, system:0x6d88cf61, require_response:False} 
  Select.req
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0150] > 00:00:00:0a:ff:ff:00:00:00:01:6d:88:cf:61
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0176] < 00:00:00:0a:ff:ff:00:00:00:02:6d:88:cf:61
24.09.2024 10:00:00 [communication][INFO    ][protocol.py:0231] < 'header': {session_id:0xffff, stream:00, function:00, p_type:0x00, s_type:0x02, system:0x6d88cf61, require_response:False} 
  Select.rsp
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0176] < 00:00:00:0a:ff:ff:00:00:00:05:80:00:00:14
24.09.2024 10:00:00 [secsgem.hsms.connection_state_machine.ConnectionStateMachine][DEBUG   ][state_machine.py:0235] State change: CONNECTED_NOT_SELECTED >> CONNECTED_SELECTED
24.09.2024 10:00:00 [secsgem.gem.communication_state_machine.CommunicationStateMachine][DEBUG   ][state_machine.py:0235] State change: NOT_COMMUNICATING >> WAIT_CRA
24.09.2024 10:00:00 [communication][INFO    ][protocol.py:0318] > 'header': {session_id:0x000a, stream:01, function:13, p_type:0x00, s_type:0x00, system:0x6d88cf62, require_response:True}  
S1F13 W
  <L> .
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0150] > 00:00:00:0c:00:0a:81:0d:00:00:6d:88:cf:62:01:00
24.09.2024 10:00:00 [communication][INFO    ][protocol.py:0231] < 'header': {session_id:0xffff, stream:00, function:00, p_type:0x00, s_type:0x05, system:0x80000014, require_response:False} 
  Linktest.req
24.09.2024 10:00:00 [communication][INFO    ][protocol.py:0430] > 'header': {session_id:0xffff, stream:00, function:00, p_type:0x00, s_type:0x06, system:0x80000014, require_response:False} 
  Linktest.rsp
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0150] > 00:00:00:0a:ff:ff:00:00:00:06:80:00:00:14
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0176] < 00:00:00:25:00:0a:01:0e:00:00:6d:88:cf:62
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0176] < 01:02:21:01:00:01:02:41:07:46:41:53:54:53:49:4d:41:09:32:2e:32:30:2e:30:30:30:32
24.09.2024 10:00:00 [communication][INFO    ][protocol.py:0275] < 'header': {session_id:0x000a, stream:01, function:14, p_type:0x00, s_type:0x00, system:0x6d88cf62, require_response:False} 
S1F14
  <L [2]
    <B 0x0>
    <L [2]
      <A "LAVTEST">
      <A "1">
    >
  > .
24.09.2024 10:00:00 [secsgem.gem.communication_state_machine.CommunicationStateMachine][DEBUG   ][state_machine.py:0235] State change: WAIT_CRA >> COMMUNICATING
24.09.2024 10:00:00 [m200.faulty.MyFaultyHandler.MyFaultyHandler][INFO    ][hosthandler.py:0136] Go online
24.09.2024 10:00:00 [communication][INFO    ][protocol.py:0273] > 'header': {session_id:0x000a, stream:01, function:17, p_type:0x00, s_type:0x00, system:0x6d88cf63, require_response:True}
S1F17 W .
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0150] > 00:00:00:0a:00:0a:81:11:00:00:6d:88:cf:63
24.09.2024 10:00:00 [bytestream][DEBUG   ][tcp_connection.py:0176] < 00:00:00:0d:00:0a:01:12:00:00:6d:88:cf:63:21:01:00
```

Now, python appears to be waiting on S1F18. In the meantime, the other side claims it had sent S1F18 long ago, in the very same second at 10:00:00.

```
4.09.2024 10:00:30 [communication][INFO    ][protocol.py:0406] > 'header': {session_id:0xffff, stream:00, function:00, p_type:0x00, s_type:0x05, system:0x6d88cf64, require_response:False} 
  Linktest.req
24.09.2024 10:00:30 [bytestream][DEBUG   ][tcp_connection.py:0150] > 00:00:00:0a:ff:ff:00:00:00:05:6d:88:cf:64
24.09.2024 10:00:30 [bytestream][DEBUG   ][tcp_connection.py:0176] < 00:00:00:0a:ff:ff:00:00:00:06:6d:88:cf:64
```

```
24.09.2024 10:00:45 [secsgem.hsms.protocol.HsmsProtocol][ERROR   ][protocol.py:0129] ignoring exception for on_connection_message_received handler
Traceback (most recent call last):
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\protocol.py", line 127, in _dispatch_block
    self._on_connection_message_received(source, result)
  File "c:\dev\test\venv\Lib\site-packages\secsgem\hsms\protocol.py", line 294, in _on_connection_message_received
    self.events.fire("message_received", {"connection": self, "message": message})
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\events.py", line 175, in fire
    self._events[event](data)
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\events.py", line 76, in __call__
    callback(data)
  File "c:\dev\test\venv\Lib\site-packages\secsgem\gem\handler.py", line 116, in _on_message_received
    self._communication_state.s1f14received()
  File "c:\dev\test\venv\Lib\site-packages\secsgem\gem\communication_state_machine.py", line 199, in s1f14received
    self._perform_transition("s1f14received")
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\state_machine.py", line 241, in _perform_transition
    transition.destination.enter(old_state)
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\state_machine.py", line 115, in enter
    self.events.fire("enter", {})
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\events.py", line 175, in fire
    self._events[event](data)
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\events.py", line 76, in __call__
    callback(data)
  File "c:\dev\test\venv\Lib\site-packages\secsgem\gem\handler.py", line 145, in _on_state_communicating
    self.events.fire("handler_communicating", {"handler": self})
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\events.py", line 175, in fire
    self._events[event](data)
  File "c:\dev\test\venv\Lib\site-packages\secsgem\common\events.py", line 76, in __call__
    callback(data)
  File "c:\dev\test\src\m200\faulty\MyFaultyHandler.py", line 26, in _on_connected
    self.go_online()
  File "c:\dev\test\venv\Lib\site-packages\secsgem\gem\hosthandler.py", line 139, in go_online
    resp = self.settings.streams_functions.decode(self.send_and_waitfor_response(self.stream_function(1, 17)()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\test\venv\Lib\site-packages\secsgem\secs\functions\streams_functions.py", line 84, in decode
    raise ValueError("Decoding failed, missing message")
ValueError: Decoding failed, missing message
24.09.2024 10:00:45 [communication][INFO    ][protocol.py:0275] < 'header': {session_id:0x000a, stream:01, function:18, p_type:0x00, s_type:0x00, system:0x6d88cf63, require_response:False} 
S1F18
  <B 0x0> .
24.09.2024 10:00:45 [m200.faulty.MyFaultyHandler.MyFaultyHandler][WARNING ][handler.py:0122] unexpected function received s01f18
{session_id:0x000a, stream:01, function:18, p_type:0x00, s_type:0x00, system:0x6d88cf63, require_response:False}
24.09.2024 10:00:45 [communication][INFO    ][protocol.py:0231] < 'header': {session_id:0xffff, stream:00, function:00, p_type:0x00, s_type:0x06, system:0x6d88cf64, require_response:False}
  Linktest.rsp
```

Unsurprisingly, taking a closer look at the pointed out line `self.settings.streams_functions.decode(self.send_and_waitfor_response(self.stream_function(1, 17)()))` reveals that `send_and_waitfor_response()` returns `None` after a while.

Why and how the message is being received exactly after the exception remains a mystery to me. As the timing is *always* on point and in this order however, I'm guessing to have triggered some solid race condition, perhaps unknowingly causing the lib to withhold the response until some timeout that happens to equal `wait_for_response`'s timeout? I'm just wildly guessing at this point.

The application I test against in that case is configured passive, DeviceID 10, port 5000, LinkTest 60, HSMS T3=45, T5=45, T6=5, T7=10, T8=5.

**Comment by bparzella** [comment]
The go_online is called in the handler for the `connected` event. This event is fired from the receive handler and still runs in the same thread as the receiver. So the receiver thread is blocked by the event calling the go_online and waiting for the response.

The message is received as soon as the go_online is aborted (10:00:30).

This makes me think about parallelizing the state machine transition events, which call the _on_connected in this case. But I'll have to look into that for future releases.

**Comment by alanchev** [comment]
That explains it! So I'll place simply `go_online()` after `enable()` in the constructor and try to ensure it's sent after S1F13. Unless there is another way to wait for `enalbe()` to finish, besides using the `handler_communicating` event?

**Comment by alanchev** [comment]
The best solution came to me just later: simply start yet another thread for all commands with outgoing communication:

```python
from threading import Thread
def _on_connected(self, params: dict):
        Thread(target=lambda: (
            self.go_online()
        )).start()
```
