### ISSUE TITLE
ValueError: State CONNECTED cannot be added since it already exists.

### ISSUE THREAD

**Issue by joshsyu** [bparzella/secsgem#28]
When I execute pytest as following command
 pytest testGemHostHandler.py
or execute sample: python3 ../samples/gem_host.py, encountering following error
`Traceback (most recent call last):
  File "../samples/gem_host.py", line 38, in <module>
    h = SampleHost("127.0.0.1", 5000, False, 0, "samplehost")
  File "../samples/gem_host.py", line 26, in __init__
    secsgem.GemHostHandler.__init__(self, address, port, active, session_id, name, custom_connection_handler)
  File "/usr/local/lib/python3.7/site-packages/secsgem/gem/hosthandler.py", line 41, in __init__
    GemHandler.__init__(self, address, port, active, session_id, name, custom_connection_handler)
  File "/usr/local/lib/python3.7/site-packages/secsgem/gem/handler.py", line 42, in __init__
    SecsHandler.__init__(self, address, port, active, session_id, name, custom_connection_handler)
  File "/usr/local/lib/python3.7/site-packages/secsgem/secs/handler.py", line 46, in __init__
    HsmsHandler.__init__(self, address, port, active, session_id, name, custom_connection_handler)
  File "/usr/local/lib/python3.7/site-packages/secsgem/hsms/handler.py", line 106, in __init__
    "on_enter_CONNECTED_SELECTED": self._on_state_select})
  File "/usr/local/lib/python3.7/site-packages/secsgem/hsms/connectionstatemachine.py", line 24, in __init__
    self.machine = Machine(model=self, states=ConnectionStateMachine.states, initial='NOT_CONNECTED', auto_transitions=False, queued=True)  # transition 1
  File "/usr/local/lib/python3.7/site-packages/transitions/extensions/nesting.py", line 339, in __init__
    _super(HierarchicalMachine, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/transitions/core.py", line 565, in __init__
    self.initial = initial
  File "/usr/local/lib/python3.7/site-packages/transitions/core.py", line 636, in initial
    self.add_state(state_name)
  File "/usr/local/lib/python3.7/site-packages/transitions/core.py", line 737, in add_state
    self.add_states(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/transitions/extensions/nesting.py", line 413, in add_states
    self.add_states(domains[1], on_enter=on_enter, on_exit=on_exit, ignore_invalid_triggers=ignore_invalid_triggers, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/transitions/extensions/nesting.py", line 416, in add_states
    raise ValueError("State {0} cannot be added since it already exists.".format(state))
**ValueError: State CONNECTED cannot be added since it already exists.**`

**Comment by bparzella** [comment]
Fixed with commit https://github.com/bparzella/secsgem/commit/70507b9b01775f3e4aa0a6febb025ba0fb2e27fd
